sudo: required

services:
  - docker

env:
  - MAKE_TARGET=mac
  - MAKE_TARGET=windows
  - MAKE_TARGET=mac-bundle
  - MAKE_TARGET=windows-bundle
  - MAKE_TARGET=arch
  - MAKE_TARGET=centos
  - MAKE_TARGET=debian
  - MAKE_TARGET=generic-linux

before_install:
  - sudo -H pip install awscli

script:
  - sudo make $MAKE_TARGET

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - if [ "$BRANCH" == "master" ]; then
      sudo make publish-${MAKE_TARGET};
    else
      sudo make publish-beta-${MAKE_TARGET};
    fi