sudo: required

dist: trusty

before_install:
  - sudo apt-get -y purge docker-engine
  - bash <(curl -fsSL https://get.docker.com/)
  - docker pull debian:jessie
  - sudo pip install awscli
  - sudo mkdir -p /root/.aws/
  - sudo bash -c "echo \"[default]\" > /root/.aws/config"
  - sudo bash -c "echo \"region = us-west-2\" > /root/.aws/config"
  - sudo bash -c "echo \"aws_secret_access_key = $AWS_SECRET_ACCESS_KEY\" > /root/.aws/config"
  - sudo bash -c "echo \"aws_access_key_id = $AWS_ACCESS_KEY_ID\" > /root/.aws/config"
  - sudo chmod 600 /root/.aws/config

script:
  - sudo make

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - if [ "$BRANCH" == "master" ]; then
      sudo make publish;
    else
      sudo make publish-beta;
    fi
